### ISSUE TITLE
Add support for sharing legendary loot toasts

### ISSUE THREAD

**Issue by mrogaski** [AIE-Guild/GreenWall#110]
Allow sharing of loot toasts for legendary items across confederations.  This appears to be handled by the SHOW_LOOT_TOAST_LEGENDARY_LOOTED event, but research into the trigger, transmission, and display details is needed.

**Comment by Torsin** [comment]
I was able to see that when I received a new legendary that the event I tossed in GreenWall.lua triggered:
```lua
	elseif event == 'SHOW_LOOT_TOAST_LEGENDARY_LOOTED' then
		SendChatMessage("Legendary", "WHISPER", nil, "Torsin")
```
 I assume that from line 416 in [AlertFrames.lua](https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/AlertFrames.lua#L427) that a line similar to:
 ```lua
local itemLink = ...;
```
 could be used within the system, instead of the simple Whisper I used to check the event, to send an appropriate message through greenwall.

**Comment by Torsin** [comment]
So I added the RegisterEvent and the following:
```lua
	elseif event == 'SHOW_LOOT_TOAST_LEGENDARY_LOOTED' then
		SendChatMessage(..., "WHISPER", nil, "Torsin")
```

I Received a Legendary, and promptly received a whisper from myself:

[Torsin]: [Soul of the Grandmaster]
To [Torsin]: [Soul of the Grandmaster]

If I knew enough about Greenwall I could use that to create the appropriate send, but since I dont....

**Comment by mrogaski** [comment]
1.9.0-alpha is up on Curse and it handles the legendary loot like it does achievements, but includes a rarity check.

Unfortunately, my participation in WoW at this point makes it impossible to test this.

**Comment by Torsin** [comment]
Would this require both sides to have the Alpha version or only the Legendary recipient?

**Comment by Torsin** [comment]
Well it didn't work on a crafted legendary, so we'll see if it works on a legendary drop...whenever that occurs.
